artifactVersion: 2.1.1
apiPackage: com.fingerprint.api
modelPackage: com.fingerprint.model
invokerPackage: com.fingerprint.sdk
groupId: com.fingerprint
artifactId: fingerprint-pro-server-api-sdk
gitHost: github.com
gitRepoId: fingerprint-pro-server-api-java-sdk
gitUserId: fingerprintjs
library: jersey2
hideGenerationTimestamp: true
