/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fingerprint.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
/**
 * BrowserDetails
 */
public class BrowserDetails {
  @SerializedName("browserName")
  private String browserName = null;

  @SerializedName("browserMajorVersion")
  private String browserMajorVersion = null;

  @SerializedName("browserFullVersion")
  private String browserFullVersion = null;

  @SerializedName("os")
  private String os = null;

  @SerializedName("osVersion")
  private String osVersion = null;

  @SerializedName("device")
  private String device = null;

  @SerializedName("userAgent")
  private String userAgent = null;

  @SerializedName("botProbability")
  private Integer botProbability = null;

  public BrowserDetails browserName(String browserName) {
    this.browserName = browserName;
    return this;
  }

   /**
   * Get browserName
   * @return browserName
  **/
  @ApiModelProperty(example = "Chrome", required = true, value = "")
  public String getBrowserName() {
    return browserName;
  }

  public void setBrowserName(String browserName) {
    this.browserName = browserName;
  }

  public BrowserDetails browserMajorVersion(String browserMajorVersion) {
    this.browserMajorVersion = browserMajorVersion;
    return this;
  }

   /**
   * Get browserMajorVersion
   * @return browserMajorVersion
  **/
  @ApiModelProperty(example = "101", required = true, value = "")
  public String getBrowserMajorVersion() {
    return browserMajorVersion;
  }

  public void setBrowserMajorVersion(String browserMajorVersion) {
    this.browserMajorVersion = browserMajorVersion;
  }

  public BrowserDetails browserFullVersion(String browserFullVersion) {
    this.browserFullVersion = browserFullVersion;
    return this;
  }

   /**
   * Get browserFullVersion
   * @return browserFullVersion
  **/
  @ApiModelProperty(example = "101.0.4951", required = true, value = "")
  public String getBrowserFullVersion() {
    return browserFullVersion;
  }

  public void setBrowserFullVersion(String browserFullVersion) {
    this.browserFullVersion = browserFullVersion;
  }

  public BrowserDetails os(String os) {
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  @ApiModelProperty(example = "Windows", required = true, value = "")
  public String getOs() {
    return os;
  }

  public void setOs(String os) {
    this.os = os;
  }

  public BrowserDetails osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * Get osVersion
   * @return osVersion
  **/
  @ApiModelProperty(example = "10", required = true, value = "")
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public BrowserDetails device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @ApiModelProperty(example = "Other", required = true, value = "")
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public BrowserDetails userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

   /**
   * Get userAgent
   * @return userAgent
  **/
  @ApiModelProperty(example = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36", required = true, value = "")
  public String getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }

  public BrowserDetails botProbability(Integer botProbability) {
    this.botProbability = botProbability;
    return this;
  }

   /**
   * Get botProbability
   * @return botProbability
  **/
  @ApiModelProperty(value = "")
  public Integer getBotProbability() {
    return botProbability;
  }

  public void setBotProbability(Integer botProbability) {
    this.botProbability = botProbability;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrowserDetails browserDetails = (BrowserDetails) o;
    return Objects.equals(this.browserName, browserDetails.browserName) &&
        Objects.equals(this.browserMajorVersion, browserDetails.browserMajorVersion) &&
        Objects.equals(this.browserFullVersion, browserDetails.browserFullVersion) &&
        Objects.equals(this.os, browserDetails.os) &&
        Objects.equals(this.osVersion, browserDetails.osVersion) &&
        Objects.equals(this.device, browserDetails.device) &&
        Objects.equals(this.userAgent, browserDetails.userAgent) &&
        Objects.equals(this.botProbability, browserDetails.botProbability);
  }

  @Override
  public int hashCode() {
    return Objects.hash(browserName, browserMajorVersion, browserFullVersion, os, osVersion, device, userAgent, botProbability);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrowserDetails {\n");
    
    sb.append("    browserName: ").append(toIndentedString(browserName)).append("\n");
    sb.append("    browserMajorVersion: ").append(toIndentedString(browserMajorVersion)).append("\n");
    sb.append("    browserFullVersion: ").append(toIndentedString(browserFullVersion)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    botProbability: ").append(toIndentedString(botProbability)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
