/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fingerprint.models;

import java.util.Objects;
import java.util.Arrays;
import com.fingerprint.models.ProductsResponseBotd;
import com.fingerprint.models.ProductsResponseIdentification;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
/**
 * Contains all the information from each activated product - Fingerprint Pro or Bot Detection
 */
@ApiModel(description = "Contains all the information from each activated product - Fingerprint Pro or Bot Detection")
public class ProductsResponse {
  @SerializedName("identification")
  private ProductsResponseIdentification identification = null;

  @SerializedName("botd")
  private ProductsResponseBotd botd = null;

  public ProductsResponse identification(ProductsResponseIdentification identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public ProductsResponseIdentification getIdentification() {
    return identification;
  }

  public void setIdentification(ProductsResponseIdentification identification) {
    this.identification = identification;
  }

  public ProductsResponse botd(ProductsResponseBotd botd) {
    this.botd = botd;
    return this;
  }

   /**
   * Get botd
   * @return botd
  **/
  @ApiModelProperty(value = "")
  public ProductsResponseBotd getBotd() {
    return botd;
  }

  public void setBotd(ProductsResponseBotd botd) {
    this.botd = botd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductsResponse productsResponse = (ProductsResponse) o;
    return Objects.equals(this.identification, productsResponse.identification) &&
        Objects.equals(this.botd, productsResponse.botd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identification, botd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductsResponse {\n");
    
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    botd: ").append(toIndentedString(botd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
