/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fingerprint.models;

import java.util.Objects;
import java.util.Arrays;
import com.fingerprint.models.ResponseVisits;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Fields &#x60;lastTimestamp&#x60; and &#x60;paginationKey&#x60; added when &#x60;limit&#x60; or &#x60;before&#x60; parameter provided and there is more data to show
 */
@ApiModel(description = "Fields `lastTimestamp` and `paginationKey` added when `limit` or `before` parameter provided and there is more data to show")
public class Response {
  @SerializedName("visitorId")
  private String visitorId = null;

  @SerializedName("visits")
  private List<ResponseVisits> visits = new ArrayList<ResponseVisits>();

  @SerializedName("lastTimestamp")
  private Long lastTimestamp = null;

  @SerializedName("paginationKey")
  private String paginationKey = null;

  public Response visitorId(String visitorId) {
    this.visitorId = visitorId;
    return this;
  }

   /**
   * Get visitorId
   * @return visitorId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVisitorId() {
    return visitorId;
  }

  public void setVisitorId(String visitorId) {
    this.visitorId = visitorId;
  }

  public Response visits(List<ResponseVisits> visits) {
    this.visits = visits;
    return this;
  }

  public Response addVisitsItem(ResponseVisits visitsItem) {
    this.visits.add(visitsItem);
    return this;
  }

   /**
   * Get visits
   * @return visits
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ResponseVisits> getVisits() {
    return visits;
  }

  public void setVisits(List<ResponseVisits> visits) {
    this.visits = visits;
  }

  public Response lastTimestamp(Long lastTimestamp) {
    this.lastTimestamp = lastTimestamp;
    return this;
  }

   /**
   * When more results are available (e.g., you scanned 200 results using &#x60;limit&#x60; parameter, but a total of 600 results are available), a special &#x60;lastTimestamp&#x60; top-level attribute is added to the response. If you want to paginate the results further in the past, you should use the value of this attribute.
   * @return lastTimestamp
  **/
  @ApiModelProperty(example = "1654815517198", value = "When more results are available (e.g., you scanned 200 results using `limit` parameter, but a total of 600 results are available), a special `lastTimestamp` top-level attribute is added to the response. If you want to paginate the results further in the past, you should use the value of this attribute.")
  public Long getLastTimestamp() {
    return lastTimestamp;
  }

  public void setLastTimestamp(Long lastTimestamp) {
    this.lastTimestamp = lastTimestamp;
  }

  public Response paginationKey(String paginationKey) {
    this.paginationKey = paginationKey;
    return this;
  }

   /**
   * Visit&#x27;s &#x60;requestId&#x60; of the last visit in the current page.
   * @return paginationKey
  **/
  @ApiModelProperty(example = "1654815517198.azN4IZ", value = "Visit's `requestId` of the last visit in the current page.")
  public String getPaginationKey() {
    return paginationKey;
  }

  public void setPaginationKey(String paginationKey) {
    this.paginationKey = paginationKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.visitorId, response.visitorId) &&
        Objects.equals(this.visits, response.visits) &&
        Objects.equals(this.lastTimestamp, response.lastTimestamp) &&
        Objects.equals(this.paginationKey, response.paginationKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visitorId, visits, lastTimestamp, paginationKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    visitorId: ").append(toIndentedString(visitorId)).append("\n");
    sb.append("    visits: ").append(toIndentedString(visits)).append("\n");
    sb.append("    lastTimestamp: ").append(toIndentedString(lastTimestamp)).append("\n");
    sb.append("    paginationKey: ").append(toIndentedString(paginationKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
