/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fingerprint.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * StSeenAt
 */
public class StSeenAt {
  @SerializedName("global")
  private OffsetDateTime global = null;

  @SerializedName("subscription")
  private OffsetDateTime subscription = null;

  public StSeenAt global(OffsetDateTime global) {
    this.global = global;
    return this;
  }

   /**
   * Get global
   * @return global
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getGlobal() {
    return global;
  }

  public void setGlobal(OffsetDateTime global) {
    this.global = global;
  }

  public StSeenAt subscription(OffsetDateTime subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getSubscription() {
    return subscription;
  }

  public void setSubscription(OffsetDateTime subscription) {
    this.subscription = subscription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StSeenAt stSeenAt = (StSeenAt) o;
    return Objects.equals(this.global, stSeenAt.global) &&
        Objects.equals(this.subscription, stSeenAt.subscription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(global, subscription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StSeenAt {\n");
    
    sb.append("    global: ").append(toIndentedString(global)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
