/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. This API can be used for data exports, decision-making, and data analysis scenarios.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fingerprint.models;

import java.util.Objects;
import java.util.Arrays;
import com.fingerprint.models.BrowserDetails;
import com.fingerprint.models.Confidence;
import com.fingerprint.models.IPLocation;
import com.fingerprint.models.StSeenAt;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;
/**
 * WebhookVisit
 */
public class WebhookVisit {
  @SerializedName("visitorId")
  private String visitorId = null;

  @SerializedName("clientReferrer")
  private String clientReferrer = null;

  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("browserDetails")
  private BrowserDetails browserDetails = null;

  @SerializedName("incognito")
  private Boolean incognito = null;

  @SerializedName("ip")
  private String ip = null;

  @SerializedName("ipLocation")
  private IPLocation ipLocation = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("time")
  private OffsetDateTime time = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("tag")
  private Map<String, Object> tag = null;

  @SerializedName("linkedId")
  private String linkedId = null;

  @SerializedName("confidence")
  private Confidence confidence = null;

  @SerializedName("visitorFound")
  private Boolean visitorFound = null;

  @SerializedName("firstSeenAt")
  private StSeenAt firstSeenAt = null;

  @SerializedName("lastSeenAt")
  private StSeenAt lastSeenAt = null;

  public WebhookVisit visitorId(String visitorId) {
    this.visitorId = visitorId;
    return this;
  }

   /**
   * Get visitorId
   * @return visitorId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVisitorId() {
    return visitorId;
  }

  public void setVisitorId(String visitorId) {
    this.visitorId = visitorId;
  }

  public WebhookVisit clientReferrer(String clientReferrer) {
    this.clientReferrer = clientReferrer;
    return this;
  }

   /**
   * Get clientReferrer
   * @return clientReferrer
  **/
  @ApiModelProperty(value = "")
  public String getClientReferrer() {
    return clientReferrer;
  }

  public void setClientReferrer(String clientReferrer) {
    this.clientReferrer = clientReferrer;
  }

  public WebhookVisit requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Unique identifier of the user&#x27;s identification request.
   * @return requestId
  **/
  @ApiModelProperty(example = "1654815516083.OX6kx8", required = true, value = "Unique identifier of the user's identification request.")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public WebhookVisit browserDetails(BrowserDetails browserDetails) {
    this.browserDetails = browserDetails;
    return this;
  }

   /**
   * Get browserDetails
   * @return browserDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public BrowserDetails getBrowserDetails() {
    return browserDetails;
  }

  public void setBrowserDetails(BrowserDetails browserDetails) {
    this.browserDetails = browserDetails;
  }

  public WebhookVisit incognito(Boolean incognito) {
    this.incognito = incognito;
    return this;
  }

   /**
   * Flag if user used incognito session.
   * @return incognito
  **/
  @ApiModelProperty(required = true, value = "Flag if user used incognito session.")
  public Boolean isisIncognito() {
    return incognito;
  }

  public void setIncognito(Boolean incognito) {
    this.incognito = incognito;
  }

  public WebhookVisit ip(String ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @ApiModelProperty(example = "8.8.8.8", required = true, value = "")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public WebhookVisit ipLocation(IPLocation ipLocation) {
    this.ipLocation = ipLocation;
    return this;
  }

   /**
   * Get ipLocation
   * @return ipLocation
  **/
  @ApiModelProperty(required = true, value = "")
  public IPLocation getIpLocation() {
    return ipLocation;
  }

  public void setIpLocation(IPLocation ipLocation) {
    this.ipLocation = ipLocation;
  }

  public WebhookVisit timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp of the event with millisecond precision in Unix time.
   * @return timestamp
  **/
  @ApiModelProperty(example = "1654815516086", required = true, value = "Timestamp of the event with millisecond precision in Unix time.")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public WebhookVisit time(OffsetDateTime time) {
    this.time = time;
    return this;
  }

   /**
   * Time expressed according to ISO 8601 in UTC format.
   * @return time
  **/
  @ApiModelProperty(example = "2022-06-09T22:58:36Z", required = true, value = "Time expressed according to ISO 8601 in UTC format.")
  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(OffsetDateTime time) {
    this.time = time;
  }

  public WebhookVisit url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Page URL from which identification request was sent.
   * @return url
  **/
  @ApiModelProperty(example = "https://some.website/path?query=params", required = true, value = "Page URL from which identification request was sent.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public WebhookVisit tag(Map<String, Object> tag) {
    this.tag = tag;
    return this;
  }

  public WebhookVisit putTagItem(String key, Object tagItem) {
    if (this.tag == null) {
      this.tag = new HashMap<String, Object>();
    }
    this.tag.put(key, tagItem);
    return this;
  }

   /**
   * A customer-provided value or an object that was sent with identification request.
   * @return tag
  **/
  @ApiModelProperty(value = "A customer-provided value or an object that was sent with identification request.")
  public Map<String, Object> getTag() {
    return tag;
  }

  public void setTag(Map<String, Object> tag) {
    this.tag = tag;
  }

  public WebhookVisit linkedId(String linkedId) {
    this.linkedId = linkedId;
    return this;
  }

   /**
   * A customer-provided id that was sent with identification request.
   * @return linkedId
  **/
  @ApiModelProperty(example = "someID", value = "A customer-provided id that was sent with identification request.")
  public String getLinkedId() {
    return linkedId;
  }

  public void setLinkedId(String linkedId) {
    this.linkedId = linkedId;
  }

  public WebhookVisit confidence(Confidence confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  @ApiModelProperty(required = true, value = "")
  public Confidence getConfidence() {
    return confidence;
  }

  public void setConfidence(Confidence confidence) {
    this.confidence = confidence;
  }

  public WebhookVisit visitorFound(Boolean visitorFound) {
    this.visitorFound = visitorFound;
    return this;
  }

   /**
   * Attribute represents if a visitor had been identified before.
   * @return visitorFound
  **/
  @ApiModelProperty(required = true, value = "Attribute represents if a visitor had been identified before.")
  public Boolean isisVisitorFound() {
    return visitorFound;
  }

  public void setVisitorFound(Boolean visitorFound) {
    this.visitorFound = visitorFound;
  }

  public WebhookVisit firstSeenAt(StSeenAt firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
    return this;
  }

   /**
   * Get firstSeenAt
   * @return firstSeenAt
  **/
  @ApiModelProperty(required = true, value = "")
  public StSeenAt getFirstSeenAt() {
    return firstSeenAt;
  }

  public void setFirstSeenAt(StSeenAt firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
  }

  public WebhookVisit lastSeenAt(StSeenAt lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
    return this;
  }

   /**
   * Get lastSeenAt
   * @return lastSeenAt
  **/
  @ApiModelProperty(required = true, value = "")
  public StSeenAt getLastSeenAt() {
    return lastSeenAt;
  }

  public void setLastSeenAt(StSeenAt lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookVisit webhookVisit = (WebhookVisit) o;
    return Objects.equals(this.visitorId, webhookVisit.visitorId) &&
        Objects.equals(this.clientReferrer, webhookVisit.clientReferrer) &&
        Objects.equals(this.requestId, webhookVisit.requestId) &&
        Objects.equals(this.browserDetails, webhookVisit.browserDetails) &&
        Objects.equals(this.incognito, webhookVisit.incognito) &&
        Objects.equals(this.ip, webhookVisit.ip) &&
        Objects.equals(this.ipLocation, webhookVisit.ipLocation) &&
        Objects.equals(this.timestamp, webhookVisit.timestamp) &&
        Objects.equals(this.time, webhookVisit.time) &&
        Objects.equals(this.url, webhookVisit.url) &&
        Objects.equals(this.tag, webhookVisit.tag) &&
        Objects.equals(this.linkedId, webhookVisit.linkedId) &&
        Objects.equals(this.confidence, webhookVisit.confidence) &&
        Objects.equals(this.visitorFound, webhookVisit.visitorFound) &&
        Objects.equals(this.firstSeenAt, webhookVisit.firstSeenAt) &&
        Objects.equals(this.lastSeenAt, webhookVisit.lastSeenAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visitorId, clientReferrer, requestId, browserDetails, incognito, ip, ipLocation, timestamp, time, url, tag, linkedId, confidence, visitorFound, firstSeenAt, lastSeenAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookVisit {\n");
    
    sb.append("    visitorId: ").append(toIndentedString(visitorId)).append("\n");
    sb.append("    clientReferrer: ").append(toIndentedString(clientReferrer)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    browserDetails: ").append(toIndentedString(browserDetails)).append("\n");
    sb.append("    incognito: ").append(toIndentedString(incognito)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    ipLocation: ").append(toIndentedString(ipLocation)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    linkedId: ").append(toIndentedString(linkedId)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    visitorFound: ").append(toIndentedString(visitorFound)).append("\n");
    sb.append("    firstSeenAt: ").append(toIndentedString(firstSeenAt)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
