/*
 * Fingerprint Pro Server API
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 3
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * VpnResultMethods
 */
@JsonPropertyOrder({
  VpnResultMethods.JSON_PROPERTY_TIMEZONE_MISMATCH,
  VpnResultMethods.JSON_PROPERTY_PUBLIC_V_P_N
})
@JsonTypeName("VpnResult_methods")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VpnResultMethods {
  public static final String JSON_PROPERTY_TIMEZONE_MISMATCH = "timezoneMismatch";
  private Boolean timezoneMismatch;

  public static final String JSON_PROPERTY_PUBLIC_V_P_N = "publicVPN";
  private Boolean publicVPN;

  public VpnResultMethods() { 
  }

  public VpnResultMethods timezoneMismatch(Boolean timezoneMismatch) {
    this.timezoneMismatch = timezoneMismatch;
    return this;
  }

   /**
   * User&#39;s browser timezone doesn&#39;t match the timezone from which the request was originally made.
   * @return timezoneMismatch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "User's browser timezone doesn't match the timezone from which the request was originally made.")
  @JsonProperty(JSON_PROPERTY_TIMEZONE_MISMATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTimezoneMismatch() {
    return timezoneMismatch;
  }


  @JsonProperty(JSON_PROPERTY_TIMEZONE_MISMATCH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezoneMismatch(Boolean timezoneMismatch) {
    this.timezoneMismatch = timezoneMismatch;
  }


  public VpnResultMethods publicVPN(Boolean publicVPN) {
    this.publicVPN = publicVPN;
    return this;
  }

   /**
   * Request IP address is owned and used by a public VPN service provider.
   * @return publicVPN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Request IP address is owned and used by a public VPN service provider.")
  @JsonProperty(JSON_PROPERTY_PUBLIC_V_P_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublicVPN() {
    return publicVPN;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_V_P_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicVPN(Boolean publicVPN) {
    this.publicVPN = publicVPN;
  }


  /**
   * Return true if this VpnResult_methods object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VpnResultMethods vpnResultMethods = (VpnResultMethods) o;
    return Objects.equals(this.timezoneMismatch, vpnResultMethods.timezoneMismatch) &&
        Objects.equals(this.publicVPN, vpnResultMethods.publicVPN);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timezoneMismatch, publicVPN);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VpnResultMethods {\n");
    sb.append("    timezoneMismatch: ").append(toIndentedString(timezoneMismatch)).append("\n");
    sb.append("    publicVPN: ").append(toIndentedString(publicVPN)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

