/*
 * Server API
 * # Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * BrowserDetails
 */
@JsonPropertyOrder({
  BrowserDetails.JSON_PROPERTY_BROWSER_NAME,
  BrowserDetails.JSON_PROPERTY_BROWSER_MAJOR_VERSION,
  BrowserDetails.JSON_PROPERTY_BROWSER_FULL_VERSION,
  BrowserDetails.JSON_PROPERTY_OS,
  BrowserDetails.JSON_PROPERTY_OS_VERSION,
  BrowserDetails.JSON_PROPERTY_DEVICE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class BrowserDetails {
  public static final String JSON_PROPERTY_BROWSER_NAME = "browser_name";
  @jakarta.annotation.Nonnull
  private String browserName;

  public static final String JSON_PROPERTY_BROWSER_MAJOR_VERSION = "browser_major_version";
  @jakarta.annotation.Nonnull
  private String browserMajorVersion;

  public static final String JSON_PROPERTY_BROWSER_FULL_VERSION = "browser_full_version";
  @jakarta.annotation.Nonnull
  private String browserFullVersion;

  public static final String JSON_PROPERTY_OS = "os";
  @jakarta.annotation.Nonnull
  private String os;

  public static final String JSON_PROPERTY_OS_VERSION = "os_version";
  @jakarta.annotation.Nonnull
  private String osVersion;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @jakarta.annotation.Nonnull
  private String device;

  public BrowserDetails() { 
  }

  public BrowserDetails browserName(@jakarta.annotation.Nonnull String browserName) {
    this.browserName = browserName;
    return this;
  }

  /**
   * Get browserName
   * @return browserName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BROWSER_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBrowserName() {
    return browserName;
  }


  @JsonProperty(value = JSON_PROPERTY_BROWSER_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBrowserName(@jakarta.annotation.Nonnull String browserName) {
    this.browserName = browserName;
  }


  public BrowserDetails browserMajorVersion(@jakarta.annotation.Nonnull String browserMajorVersion) {
    this.browserMajorVersion = browserMajorVersion;
    return this;
  }

  /**
   * Get browserMajorVersion
   * @return browserMajorVersion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BROWSER_MAJOR_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBrowserMajorVersion() {
    return browserMajorVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_BROWSER_MAJOR_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBrowserMajorVersion(@jakarta.annotation.Nonnull String browserMajorVersion) {
    this.browserMajorVersion = browserMajorVersion;
  }


  public BrowserDetails browserFullVersion(@jakarta.annotation.Nonnull String browserFullVersion) {
    this.browserFullVersion = browserFullVersion;
    return this;
  }

  /**
   * Get browserFullVersion
   * @return browserFullVersion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BROWSER_FULL_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBrowserFullVersion() {
    return browserFullVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_BROWSER_FULL_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBrowserFullVersion(@jakarta.annotation.Nonnull String browserFullVersion) {
    this.browserFullVersion = browserFullVersion;
  }


  public BrowserDetails os(@jakarta.annotation.Nonnull String os) {
    this.os = os;
    return this;
  }

  /**
   * Get os
   * @return os
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOs() {
    return os;
  }


  @JsonProperty(value = JSON_PROPERTY_OS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOs(@jakarta.annotation.Nonnull String os) {
    this.os = os;
  }


  public BrowserDetails osVersion(@jakarta.annotation.Nonnull String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Get osVersion
   * @return osVersion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOsVersion() {
    return osVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOsVersion(@jakarta.annotation.Nonnull String osVersion) {
    this.osVersion = osVersion;
  }


  public BrowserDetails device(@jakarta.annotation.Nonnull String device) {
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDevice() {
    return device;
  }


  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDevice(@jakarta.annotation.Nonnull String device) {
    this.device = device;
  }


  /**
   * Return true if this BrowserDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrowserDetails browserDetails = (BrowserDetails) o;
    return Objects.equals(this.browserName, browserDetails.browserName) &&
        Objects.equals(this.browserMajorVersion, browserDetails.browserMajorVersion) &&
        Objects.equals(this.browserFullVersion, browserDetails.browserFullVersion) &&
        Objects.equals(this.os, browserDetails.os) &&
        Objects.equals(this.osVersion, browserDetails.osVersion) &&
        Objects.equals(this.device, browserDetails.device);
  }

  @Override
  public int hashCode() {
    return Objects.hash(browserName, browserMajorVersion, browserFullVersion, os, osVersion, device);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrowserDetails {\n");
    sb.append("    browserName: ").append(toIndentedString(browserName)).append("\n");
    sb.append("    browserMajorVersion: ").append(toIndentedString(browserMajorVersion)).append("\n");
    sb.append("    browserFullVersion: ").append(toIndentedString(browserFullVersion)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

