/*
 * Server API
 * # Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Error code: * `request_cannot_be_parsed` - The query parameters or JSON payload contains some errors   that prevented us from parsing it (wrong type/surpassed limits). * `secret_api_key_required` - secret API key in header is missing or empty. * `secret_api_key_not_found` - No Fingerprint application found for specified secret API key. * `public_api_key_required` - public API key in header is missing or empty. * `public_api_key_not_found` - No Fingerprint application found for specified public API key. * `subscription_not_active` - Fingerprint application is not active. * `wrong_region` - Server and application region differ. * `feature_not_enabled` - This feature (for example, Delete API) is not enabled for your application. * `request_not_found` - The specified event ID was not found. It never existed, expired, or it has been deleted. * `visitor_not_found` - The specified visitor ID was not found. It never existed or it may have already been deleted. * `too_many_requests` - The limit on secret API key requests per second has been exceeded. * `state_not_ready` - The event specified with event ID is   not ready for updates yet. Try again.   This error happens in rare cases when update API is called immediately   after receiving the event ID on the client. In case you need to send   information right away, we recommend using the JS agent API instead. * `failed` - Internal server error. * `event_not_found` - The specified event ID was not found. It never existed, expired, or it has been deleted. * `missing_module` - The request is invalid because it is missing a required module. * `payload_too_large` - The request payload is too large and cannot be processed. 
 */
public enum ErrorCode {
  
  REQUEST_CANNOT_BE_PARSED("request_cannot_be_parsed"),
  
  SECRET_API_KEY_REQUIRED("secret_api_key_required"),
  
  SECRET_API_KEY_NOT_FOUND("secret_api_key_not_found"),
  
  PUBLIC_API_KEY_REQUIRED("public_api_key_required"),
  
  PUBLIC_API_KEY_NOT_FOUND("public_api_key_not_found"),
  
  SUBSCRIPTION_NOT_ACTIVE("subscription_not_active"),
  
  WRONG_REGION("wrong_region"),
  
  FEATURE_NOT_ENABLED("feature_not_enabled"),
  
  REQUEST_NOT_FOUND("request_not_found"),
  
  VISITOR_NOT_FOUND("visitor_not_found"),
  
  TOO_MANY_REQUESTS("too_many_requests"),
  
  STATE_NOT_READY("state_not_ready"),
  
  FAILED("failed"),
  
  EVENT_NOT_FOUND("event_not_found"),
  
  MISSING_MODULE("missing_module"),
  
  PAYLOAD_TOO_LARGE("payload_too_large");

  private String value;

  ErrorCode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ErrorCode fromValue(String value) {
    for (ErrorCode b : ErrorCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

