/*
 * Server API
 * # Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fingerprint.model.Geolocation;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * IPInfoV6
 */
@JsonPropertyOrder({
  IPInfoV6.JSON_PROPERTY_ADDRESS,
  IPInfoV6.JSON_PROPERTY_GEOLOCATION,
  IPInfoV6.JSON_PROPERTY_ASN,
  IPInfoV6.JSON_PROPERTY_ASN_NAME,
  IPInfoV6.JSON_PROPERTY_ASN_NETWORK,
  IPInfoV6.JSON_PROPERTY_DATACENTER_RESULT,
  IPInfoV6.JSON_PROPERTY_DATACENTER_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class IPInfoV6 {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_GEOLOCATION = "geolocation";
  @jakarta.annotation.Nullable
  private Geolocation geolocation;

  public static final String JSON_PROPERTY_ASN = "asn";
  @jakarta.annotation.Nullable
  private String asn;

  public static final String JSON_PROPERTY_ASN_NAME = "asn_name";
  @jakarta.annotation.Nullable
  private String asnName;

  public static final String JSON_PROPERTY_ASN_NETWORK = "asn_network";
  @jakarta.annotation.Nullable
  private String asnNetwork;

  public static final String JSON_PROPERTY_DATACENTER_RESULT = "datacenter_result";
  @jakarta.annotation.Nullable
  private Boolean datacenterResult;

  public static final String JSON_PROPERTY_DATACENTER_NAME = "datacenter_name";
  @jakarta.annotation.Nullable
  private String datacenterName;

  public IPInfoV6() { 
  }

  public IPInfoV6 address(@jakarta.annotation.Nonnull String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }


  public IPInfoV6 geolocation(@jakarta.annotation.Nullable Geolocation geolocation) {
    this.geolocation = geolocation;
    return this;
  }

  /**
   * Get geolocation
   * @return geolocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GEOLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Geolocation getGeolocation() {
    return geolocation;
  }


  @JsonProperty(value = JSON_PROPERTY_GEOLOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGeolocation(@jakarta.annotation.Nullable Geolocation geolocation) {
    this.geolocation = geolocation;
  }


  public IPInfoV6 asn(@jakarta.annotation.Nullable String asn) {
    this.asn = asn;
    return this;
  }

  /**
   * Get asn
   * @return asn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAsn() {
    return asn;
  }


  @JsonProperty(value = JSON_PROPERTY_ASN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsn(@jakarta.annotation.Nullable String asn) {
    this.asn = asn;
  }


  public IPInfoV6 asnName(@jakarta.annotation.Nullable String asnName) {
    this.asnName = asnName;
    return this;
  }

  /**
   * Get asnName
   * @return asnName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAsnName() {
    return asnName;
  }


  @JsonProperty(value = JSON_PROPERTY_ASN_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsnName(@jakarta.annotation.Nullable String asnName) {
    this.asnName = asnName;
  }


  public IPInfoV6 asnNetwork(@jakarta.annotation.Nullable String asnNetwork) {
    this.asnNetwork = asnNetwork;
    return this;
  }

  /**
   * Get asnNetwork
   * @return asnNetwork
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASN_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAsnNetwork() {
    return asnNetwork;
  }


  @JsonProperty(value = JSON_PROPERTY_ASN_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAsnNetwork(@jakarta.annotation.Nullable String asnNetwork) {
    this.asnNetwork = asnNetwork;
  }


  public IPInfoV6 datacenterResult(@jakarta.annotation.Nullable Boolean datacenterResult) {
    this.datacenterResult = datacenterResult;
    return this;
  }

  /**
   * Get datacenterResult
   * @return datacenterResult
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATACENTER_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDatacenterResult() {
    return datacenterResult;
  }


  @JsonProperty(value = JSON_PROPERTY_DATACENTER_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatacenterResult(@jakarta.annotation.Nullable Boolean datacenterResult) {
    this.datacenterResult = datacenterResult;
  }


  public IPInfoV6 datacenterName(@jakarta.annotation.Nullable String datacenterName) {
    this.datacenterName = datacenterName;
    return this;
  }

  /**
   * Get datacenterName
   * @return datacenterName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATACENTER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatacenterName() {
    return datacenterName;
  }


  @JsonProperty(value = JSON_PROPERTY_DATACENTER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatacenterName(@jakarta.annotation.Nullable String datacenterName) {
    this.datacenterName = datacenterName;
  }


  /**
   * Return true if this IPInfoV6 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPInfoV6 ipInfoV6 = (IPInfoV6) o;
    return Objects.equals(this.address, ipInfoV6.address) &&
        Objects.equals(this.geolocation, ipInfoV6.geolocation) &&
        Objects.equals(this.asn, ipInfoV6.asn) &&
        Objects.equals(this.asnName, ipInfoV6.asnName) &&
        Objects.equals(this.asnNetwork, ipInfoV6.asnNetwork) &&
        Objects.equals(this.datacenterResult, ipInfoV6.datacenterResult) &&
        Objects.equals(this.datacenterName, ipInfoV6.datacenterName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, geolocation, asn, asnName, asnNetwork, datacenterResult, datacenterName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPInfoV6 {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("    asn: ").append(toIndentedString(asn)).append("\n");
    sb.append("    asnName: ").append(toIndentedString(asnName)).append("\n");
    sb.append("    asnNetwork: ").append(toIndentedString(asnNetwork)).append("\n");
    sb.append("    datacenterResult: ").append(toIndentedString(datacenterResult)).append("\n");
    sb.append("    datacenterName: ").append(toIndentedString(datacenterName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

