/*
 * Server API
 * # Overview Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * Is absent if the velocity data could not be generated for the visitor Id. 
 */
@JsonPropertyOrder({
  VelocityData.JSON_PROPERTY_5MINUTES,
  VelocityData.JSON_PROPERTY_1HOUR,
  VelocityData.JSON_PROPERTY_24HOURS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class VelocityData {
  public static final String JSON_PROPERTY_5MINUTES = "5_minutes";
  @jakarta.annotation.Nonnull
  private Integer _5minutes;

  public static final String JSON_PROPERTY_1HOUR = "1_hour";
  @jakarta.annotation.Nonnull
  private Integer _1hour;

  public static final String JSON_PROPERTY_24HOURS = "24_hours";
  @jakarta.annotation.Nullable
  private Integer _24hours;

  public VelocityData() { 
  }

  public VelocityData _5minutes(@jakarta.annotation.Nonnull Integer _5minutes) {
    this._5minutes = _5minutes;
    return this;
  }

  /**
   * Count for the last 5 minutes of velocity data, from the time of the event. 
   * @return _5minutes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_5MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer get5minutes() {
    return _5minutes;
  }


  @JsonProperty(value = JSON_PROPERTY_5MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set5minutes(@jakarta.annotation.Nonnull Integer _5minutes) {
    this._5minutes = _5minutes;
  }


  public VelocityData _1hour(@jakarta.annotation.Nonnull Integer _1hour) {
    this._1hour = _1hour;
    return this;
  }

  /**
   * Count for the last 1 hour of velocity data, from the time of the event. 
   * @return _1hour
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_1HOUR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer get1hour() {
    return _1hour;
  }


  @JsonProperty(value = JSON_PROPERTY_1HOUR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set1hour(@jakarta.annotation.Nonnull Integer _1hour) {
    this._1hour = _1hour;
  }


  public VelocityData _24hours(@jakarta.annotation.Nullable Integer _24hours) {
    this._24hours = _24hours;
    return this;
  }

  /**
   * The &#x60;24_hours&#x60; interval of &#x60;distinct_ip&#x60;, &#x60;distinct_linked_id&#x60;, &#x60;distinct_country&#x60;, &#x60;distinct_ip_by_linked_id&#x60; and &#x60;distinct_visitor_id_by_linked_id&#x60; will be omitted if the number of &#x60;events&#x60; for the visitor Id in the last 24 hours (&#x60;events.[&#39;24_hours&#39;]&#x60;) is higher than 20.000. 
   * @return _24hours
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_24HOURS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer get24hours() {
    return _24hours;
  }


  @JsonProperty(value = JSON_PROPERTY_24HOURS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void set24hours(@jakarta.annotation.Nullable Integer _24hours) {
    this._24hours = _24hours;
  }


  /**
   * Return true if this VelocityData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VelocityData velocityData = (VelocityData) o;
    return Objects.equals(this._5minutes, velocityData._5minutes) &&
        Objects.equals(this._1hour, velocityData._1hour) &&
        Objects.equals(this._24hours, velocityData._24hours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_5minutes, _1hour, _24hours);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VelocityData {\n");
    sb.append("    _5minutes: ").append(toIndentedString(_5minutes)).append("\n");
    sb.append("    _1hour: ").append(toIndentedString(_1hour)).append("\n");
    sb.append("    _24hours: ").append(toIndentedString(_24hours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

