name: Functional Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  functional_tests:
    name: "Functional Tests Java ${{ matrix.java }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '${{ matrix.java }}'
          cache: 'gradle'
      - run: ./gradlew runFunctionalTests
        env:
          FPJS_API_SECRET: "${{ secrets.FPJS_API_SECRET }}"
          FPJS_API_REGION: "${{ secrets.FPJS_API_REGION }}"
          FPJS_VISITOR_ID: "${{ secrets.FPJS_VISITOR_ID }}"
          FPJS_REQUEST_ID: "${{ secrets.FPJS_REQUEST_ID }}"