name: Functional Tests

on:
  pull_request_target:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  functional_tests:
    name: "Functional Tests Java ${{ matrix.java }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '${{ matrix.java }}'
          cache: 'gradle'
      - run: ./gradlew runFunctionalTests
        env:
          FPJS_API_SECRET: "${{ secrets.FPJS_API_SECRET }}"
          FPJS_API_REGION: "${{ secrets.FPJS_API_REGION }}"
          FPJS_VISITOR_ID: "${{ secrets.FPJS_VISITOR_ID }}"
          FPJS_REQUEST_ID: "${{ secrets.FPJS_REQUEST_ID }}"

  report_status:
    needs: functional_tests
    if: always()
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
    with:
      notification_title: 'Java SDK Functional Tests has {status_message}'
      job_status: ${{ needs.functional_tests.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
