name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      appId: ${{ vars.APP_ID }}
      runnerAppId: ${{ vars.RUNNER_APP_ID }}
      version-command: bash ./changeset-version.sh
      publish-command: bash ./changeset-publish.sh
      language: java
      language-version: '11'
      java-version: '11'
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      RUNNER_APP_PRIVATE_KEY: ${{ secrets.RUNNER_APP_PRIVATE_KEY }}
