name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release Version
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Yarn dependencies
        run: yarn install --cwd=release

      - name: Release
        uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@v1
        with:          
          appId: ${{ vars.APP_ID }}
          language: java
          java-version: '8'
          prepare-command: |
            ./gradlew jar --no-daemon
            ./gradlew publishToMavenLocal
        secrets:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          HUSKY: 0

      - name: Publish
        run: ./gradlew publishToMavenLocal