name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: 'Build project, run CI checks and publish new release'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@v1
    with:          
      appId: ${{ vars.APP_ID }}
      language: java
      language-version: '8'
      java-version: '8'
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
