name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release Version
    runs-on: "ubuntu:latest"
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

      - name: Install Yarn dependencies
        run: yarn install --cwd=release

      - name: Release
        run: ./release/node_modules/.bin/semantic-release --extends ./release/.releaserc.js -d
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          HUSKY: 0