name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release Version
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew jar --no-daemon

      - name: Install Yarn dependencies
        run: yarn install --cwd=release

      - name: Release
        with:
          appId: ${{ vars.APP_ID }}
        run: ./release/node_modules/.bin/semantic-release --extends ./release/.releaserc.js        
        secrets:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          HUSKY: 0

      - name: Publish
        run: ./gradlew publishToMavenLocal