name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Java ${{ matrix.Java }}
    strategy:
      matrix:
        java: [ '11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '${{ matrix.java }}'
      - run: ./gradlew test
