name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Java ${{ matrix.Java }}
    strategy:
      matrix:
        java: [ '8', '11' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '${{ matrix.java }}'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon